#!/bin/bash
cd /vhs/kangle/nodewww/webftp/vhost/view/ws/
wget https://raw.githubusercontent.com/scncwqs/kangle/master/httptohttps/ssl.html -O ssl.html
cd /vhs/kangle/nodewww/webftp/vhost/control/
wget https://raw.githubusercontent.com/scncwqs/kangle/master/httptohttps/index.ctl.php -O index.ctl.php
